name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the angularapp Docker image
      run: |
        docker login ghcr.io -u vishuhanda -p ${{ secrets.GITHUB_TOKEN }}
        docker build -t ghcr.io/vishuhanda/githubangular:1.0 . 
        docker push ghcr.io/vishuhanda/githubangular:1.0
