name: publish

on: [pull_request]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: Login to GitHub Container Registry
      uses: actions/checkout@v2.5.0 # Checking out the repo

    - name: Build and publish "head" Docker image
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: angular_app_demo # Provide Docker image name
        image-tag: 4.0 # Provide Docker image tag
