name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the angularapp Docker image
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: demoangularapp
        registry: ghcr.io
        username: vishuhanda
        password: ${{ secrets.GITHUB_TOKEN }}
