name: Jobs for practice

on: [push]


jobs:
    my_first_job:
      runs-on: ubuntu-latest
      steps:
      - name: first step
        id : first_step
        env : 
          GREETING : hello
        run : |
          echo $GREETING

      - name: seconds step
        id : second_step
        env : 
          NOWGREETING :  $ {{ GITHUB_EVENT_NAME }}  
        run : |
          echo $NOWGREETING