name: Jobs for practice

on: [push]


jobs:
    my_first_job:
      runs-on: ubuntu-latest
      env:
        CHKTHIS : THISISNEWVAL
      steps:
      - name: first step
        id : first_step
        env : 
          GREETING : hello
        run : |
          echo $GREETING

      - name: seconds step
        id : second_step
        env : 
          NOWGREETING :  TRYTHIS  
        run : |
          echo this is how to access env vars $GITHUB_EVENT_NAME and ${{ env.CHKTHIS }} and  ${{ env.NOWGREETING }} and ok $env.NOWGREETING and ok second $NOWGREETING